module.exports = {
  name: '探小店后台',
  prefix: 'tan_shop_',
  footerText: '探小店后台   © 2017 中山食探工作室',
  logo: '/st.jpg',
  iconFontCSS: '/iconfont.css',
  iconFontJS: '/iconfont.js',
  baseURL: 'http://localhost:3050/api/v1',
  YQL: ['http://www.zuimeitianqi.com'],
  CORS: ['http://localhost:7000'],
  openPages: ['/login'],
  apiPrefix: '/api/v1',
  api: {
    userLogin: '/token/admin',
    userLogout: '/user/logout',
    userInfo: '/userInfo',
    users: '/users',
    category: '/category/all',
    posts: '/posts',
    user: '/user/:id',
    dashboard: '/dashboard',
  },
}
