module.exports = {
    permission: {
        product: [
            'list',
            'create',
            'updateBase',
            'updateDetail',
            'updateParams',
            'stockPrice',
            'pullOnOff',
            'remove',
            'createBuyNow',
            'oneBuyNow',
            'one',
        ],
        order: [
            'list',
            'one',
            'price',
            'delivery',
            'issue',
            'close',
            'remove',
        ],
        category: [
            'list',
            'create',
            'update',
            'remove',
            'managerProduct',
        ],
        theme: [
            'list',
            'create',
            'update',
            'remove',
            'pullOnOff',
            'managerProduct',
            'setRank',
        ],
        express: [
            'list',
            'create',
            'update',
            'remove',
        ],
        user: [
            'list',
            'one',
        ],
        admin: [
            'list',
            'create',
            'update',
            'remove',
            'pullStatus',
            'chatlist',
            'auth',
        ],
        menu: [
            'list',
            'create',
            'update',
            'remove',
        ],
        resource: [
            'list',
            'create',
            'update',
            'remove',
        ],
        role: [
            'list',
            'create',
            'update',
            'remove',
            'auth',
        ],
    }
}