module.exports = [
  {
    id: 1,
    icon: 'home',
    name: '首页',
    router: '/dashboard',
  },
  {
    id: 3,
    bpid: 1,
    name: '商品管理',
    icon: 'barcode',
    router: '/product',
  },
  {
    id: 5,
    bpid: 1,
    name: '分类管理',
    icon: 'bars',
    router: '/category',
  },
  {
    id: 7,
    bpid: 1,
    name: '订单管理',
    icon: 'shopping-cart',
    router: '/order',
  },
  {
    id: 2,
    bpid: 1,
    name: '用户管理',
    icon: 'user',
    router: '/user',
  },
  {
    id: 21,
    mpid: -1,
    bpid: 2,
    name: 'User Detail',
    router: '/user/:id',
  },
  {
    id: 6,
    bpid: 1,
    name: '系统管理',
    icon: 'setting',
  },
  {
    id: 61,
    bpid: 6,
    mpid: 6,
    name: '管理员管理',
    router: '/navigation/navigation1',
  },
  {
    id: 62,
    bpid: 6,
    mpid: 6,
    name: '权限管理',
    router: '/navigation/navigation2',
  },
  {
    id: 621,
    bpid: 62,
    mpid: 62,
    name: '分配角色',
    router: '/navigation/navigation2/navigation1',
  },
  {
    id: 622,
    bpid: 62,
    mpid: 62,
    name: '分配权限',
    router: '/navigation/navigation2/navigation2',
  },
]
